### ISSUE TITLE
I can install from a git clone, but not from git directly neither from pipy

### ISSUE THREAD

**Issue by UnixJunkie** [swamidasslab/CROC#1]
```bash
# trying from pipy
# pip3 install CROC
Defaulting to user installation because normal site-packages is not writeable
Collecting CROC
  Using cached CROC-1.2.6.tar.gz (26 kB)
  Preparing metadata (setup.py) ... done
Discarding https://files.pythonhosted.org/packages/a6/12/0fdedd86f171b35d2a4c184d115d6a9795d62671b4f4ef43b57e934b3926/CROC-1.2.6.tar.gz#sha256=a3b9c30064e6d70d757fd8fec5b49bbe80a218cfce483e0dad04ed1207ac7690 (from https://pypi.org/simple/croc/): Requested CROC from https://files.pythonhosted.org/packages/a6/12/0fdedd86f171b35d2a4c184d115d6a9795d62671b4f4ef43b57e934b3926/CROC-1.2.6.tar.gz#sha256=a3b9c30064e6d70d757fd8fec5b49bbe80a218cfce483e0dad04ed1207ac7690 has inconsistent version: filename has '1.2.6', but metadata has 'unknown'
  Using cached CROC-1.2.4.tar.gz (26 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-2mf_nt4o/croc_96434a1c2fab4ec1b16f287a6637ad30/setup.py", line 26, in <module>
          version, cmdclass = get_version_and_cmdclass("CROC")
        File "/tmp/pip-install-2mf_nt4o/croc_96434a1c2fab4ec1b16f287a6637ad30/setup.py", line 22, in get_version_and_cmdclass
          spec.loader.exec_module(module)  # type: ignore
        File "<frozen importlib._bootstrap_external>", line 879, in exec_module
        File "<frozen importlib._bootstrap_external>", line 1016, in get_code
        File "<frozen importlib._bootstrap_external>", line 1073, in get_data
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-2mf_nt4o/croc_96434a1c2fab4ec1b16f287a6637ad30/CROC/_version.py'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

# trying from the git repos directly
# pip3 install https://github.com/swamidasslab/CROC.git
Defaulting to user installation because normal site-packages is not writeable
Collecting https://github.com/swamidasslab/CROC.git
  Downloading https://github.com/swamidasslab/CROC.git
     - 187.8 kB 19.1 MB/s 0:00:00
  ERROR: Cannot unpack file /tmp/pip-unpack-nd2x_lad/CROC.git (downloaded from /tmp/pip-req-build-wn4w4wnd, content-type: text/html; charset=utf-8); cannot detect archive format
ERROR: Cannot determine archive format of /tmp/pip-req-build-wn4w4wnd

**Comment by UnixJunkie** [comment]
But 'pip3 install .` inside of a git clone just works (so the issue is not a total show stopper).

**Comment by swamidass** [comment]
Any idea what's wrong and how to fix it?

**Comment by swamidass** [comment]
Any idea what's wrong and how to fix it?
